### ISSUE TITLE
README request

### ISSUE THREAD

**Issue by StevenACoffman** [cachapa/sql_crdt#2]
Hello, I am guessing that `hlc` is hybrid-logical clocks. Can you add a footnote to your readme that unpacks this a bit?

"HLCs use a combination of system timestamp and logical timestamp to have versions as date-time, which can be ordered." I would also be curious to know what data primitive the underlying postgres/sqlite uses to store these.

**Comment by cachapa** [comment]
Thanks for the suggestion. I copied over the text explaining HLCs from [crdt](https://github.com/cachapa/crdt).

I prefer to not get into a lot of detail on the how HLC works since it kind of snowballs into explaining CRDTs as well, which I feel are already better covered in the linked resources than what I could accomplish.

In sql_crdt, HLCs are stored as strings as `ISO8601 date`-`counter`-`node id`.
This has a number of useful properties:
* Stores the entire value in a single column.
* Is human-readable.
* Ascii comparisons work as intended.

**Comment by StevenACoffman** [comment]
Thanks! I was very curious if the representation allowed sorting via regular SQL queries  (outside of Dart) somehow.

**Comment by cachapa** [comment]
Yeah, that property is used a lot inside the package as well, e.g. merge conflict resolution is [performed directly in the UPSERT](https://github.com/cachapa/sql_crdt/blob/master/lib/src/sql_crdt.dart#L211) rather than doing dart <-> SQL roundtrips.
